rootProject.name = 'ticket-play'

include 'tiple-concert', 'tiple-core', 'tiple-member', 'tiple-sse', 'tiple-ticket'

project(':tiple-core').projectDir = file('tiple-core')
project(':tiple-concert').projectDir = file('tiple-concert')
project(':tiple-member').projectDir = file('tiple-member')
project(':tiple-sse').projectDir = file('tiple-sse')
project(':tiple-ticket').projectDir = file('tiple-ticket')
