# 공통 설정
spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true # Hibernate가 생성하는 SQL 쿼리를 사람이 읽기 쉬운 형태로 포맷팅

server:
  port: ${port:5003}
  forward-headers-strategy: native # 서버가 요청 헤더를 어떻게 처리할지 지정

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: ${jwt.secret}
  expiration-ms: 86400000

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/tiple
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none  # JPA에 의한 테이블 자동 생성 비활성화
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql
