upstream spring_servers {
    server spring-server:8083;
    server spring-server2:8084;
    server spring-server3:8085;
}

server {
    listen 80;
    server_name localhost;

    # 헤더 및 인코딩 설정 추가
    charset utf-8;
    source_charset utf-8;

    location / {
        proxy_pass http://spring_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
