upstream tiple-concert {
    server ticket-concert:8081;
}

upstream tiple-auth {
    server ticket-auth:8082;
}

upstream tiple-member {
    server ticket-payment:8083;
}

upstream tiple-sse {
    server ticket-payment:8084;
}

upstream tiple-ticket {
    server ticket-payment:8085;
}

server {
    listen 80;
    server_name localhost;

    # Health Check
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    # Concert Service
    location /api/concerts {
        proxy_pass http://tiple-concert;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Auth Service
    location /api/auth {
        proxy_pass http://tiple-auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Member Service
    location /api/members {
        proxy_pass http://tiple-member;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Notification Service
    location /api/ticket-reservations {
        proxy_pass http://tiple-ticket;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ticket Service
    location /api/ticket-waiting {
        proxy_pass http://tiple-ticket;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ticket Service
    location /api/notifications {
        proxy_pass http://tiple-sse;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # Static files or frontend
    location / {
        proxy_pass http://ticket-concert;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}